name: Generate UML 

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: coursier/setup-action@v1
        with:
          jvm: adopt:11
          apps: sbtn bloop 

      - name: install scala2pantuml
        run: cs install --channel https://git.io/Jqv1i scala2plantuml

      - name: generate uml
        run: scala2plantuml -s "./AircraftWar/src" "AircraftWar."
          