name: Generate UML 

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: coursier/setup-action@v1
        with:
          jvm: adopt:11
          apps: sbtn 

      - name: install graphviz
        run: apt update && apt install graphviz -y

      - name: generate uml
        run: |
          cd .. 
          git clone https://github.com/tizuck/scala-uml.git
          cd scala-uml
          sbt "runMain app.ci.Main -f ../AircraftWar/AircraftWar/src -o ."
          